Mika/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/urls.py
from django.contrib import admin
from django.urls import path
from app import views

app_name = "app"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('home/', views.home, name='home'),
    path('libraries/', views.lib, name='libraries'),
    path('contactUs/', views.contact, name='contacts'),
    path('pay', views.pay, name='pay')

]

app/models.py
from django.db import models

# Create your models here.

app/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from django import forms
from django.forms.widgets import PasswordInput, TextInput


# Register a User

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


# login a user

class LogInForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())

app/views.py
import json
import requests
from django.http import HttpResponse
from django.shortcuts import render, redirect
from requests.auth import HTTPBasicAuth
from .credentials import MpesaAccessToken, LipanaMpesaPpassword
from .forms import RegisterForm, LogInForm


# ------------------index page-------------------------------------
def index(request):
    return render(request, 'index.html')


# ------------------register page/View-------------------------------------
def register(request):
    form = RegisterForm()

    if request.method == "POST":
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()

    context = {'form': form}

    return render(request, 'register.html', context=context)


# ------------------login page-------------------------------------
def login(request):
    return render(request, 'login.html')


# ------------------home page-------------------------------------
def home(request):
    return render(request, 'home.html')


def lib(request):
    return render(request, 'libraries.html')


def contact(request):
    return render(request, 'contacts.html')


def token(request):
    consumer_key = '77bgGpmlOxlgJu6oEXhEgUgnu0j2WYxA'
    consumer_secret = 'viM8ejHgtEmtPTHd'
    api_url = 'https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials'

    r = requests.get(api_url, auth=HTTPBasicAuth(consumer_key, consumer_secret))
    mpesa_access_token = json.loads(r.text)
    validated_mpesa_access_token = mpesa_access_token["access_token"]

    return render(request, 'token.html', {"token": validated_mpesa_access_token})


def pay(request):
    if request.method == "POST":
        phone = request.POST['phone']
        amount = request.POST['amount']
        access_token = MpesaAccessToken.validated_mpesa_access_token
        api_url = "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
        headers = {"Authorization": "Bearer %s" % access_token}
        request_data = {
            "BusinessShortCode": LipanaMpesaPpassword.Business_short_code,
            "Password": LipanaMpesaPpassword.decode_password,
            "Timestamp": LipanaMpesaPpassword.lipa_time,
            "TransactionType": "CustomerPayBillOnline",
            "Amount": amount,
            "PartyA": phone,
            "PartyB": LipanaMpesaPpassword.Business_short_code,
            "PhoneNumber": phone,
            "CallBackURL": "https://sandbox.safaricom.co.ke/mpesa/",
            "AccountReference": "Alex Maina",
            "TransactionDesc": "Mika Hub Limited "
        }
        response = requests.post(api_url, json=request_data, headers=headers)
        return HttpResponse("success")

    return render(request, 'pay.html')


def stk(request):
    return render(request, 'pay.html', {'navbar': 'app'})

templates/base.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>MIKA HUB</title>

    <!-- Favicons -->
  <link href="{% static 'img/mh.png' %}" rel="icon">
    <link href="{% static 'img/mh.png'%}" rel="apple-touch-icon">

        <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Roboto:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Work+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">



{#     <---Bootstrap theme--->#}
    <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/morph/bootstrap.min.css">

{#    /* <---main css file--->#}
    <link rel="stylesheet" type="text/css " href="{% static 'css/main.css' %}">

    <style>
        body {
            /* Set the background image and adjust properties */
            background-image: url('{% static "img/bg_1.png" %}');
            background-size: cover;
            background-repeat: no-repeat;
            /* Optionally, you can set other background properties like position or attachment */
        }
    </style>

</head>
<body>

{#    <---navbar-->#}
<div class="row">
    <nav class="navbar navbar-expand-lg bg-black justify-content-end">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img src="{% static 'img/mh.png' %}" alt="Bootstrap" width="130" height="60">
        </a>
      </div>
      <div class="container-fluid">
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link " aria-current="page" href="{% url 'app:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app:libraries' %}">Libraries</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app:contacts' %}">Contact us</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
</div>


    <div class="container text-center" >

        <br>
        <br>
        <br>
        <div class="col-5"></div>



            {% block content %}

                <div class="col-4">


                </div>
            {% endblock %}
        <div class="col-3"></div>
    </div>

{#<---main js--->#}
{#<script src="{% static 'js/main' %}"></script>#}

{#<---bootstrap js--->#}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>

</body>
</html>

templates/base2.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>MIKA HUB</title>

    <!-- Favicons -->
  <link href="{% static 'img/mh.png' %}" rel="icon">
    <link href="{% static 'img/mh.png'%}" rel="apple-touch-icon">

        <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Roboto:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Work+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">



{#     <---Bootstrap theme--->#}
    <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/morph/bootstrap.min.css">

{#    /* <---main css file--->#}
    <link rel="stylesheet" type="text/css " href="{% static 'css/main.css' %}">

    <style>
        body {
            /* Set the background image and adjust properties */
            background-image: url('{% static "img/bg_1.png" %}');
            background-size: cover;
            background-repeat: no-repeat;
            /* Optionally, you can set other background properties like position or attachment */
        }
    </style>

</head>
<body>

{#    <---navbar-->#}
<div class="row">
    <nav class="navbar navbar-expand-lg bg-black justify-content-end">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img src="{% static 'img/mh.png' %}" alt="Bootstrap" width="130" height="60">
        </a>
      </div>
      <div class="container-fluid">

{#      -----------------------AUTHENTICATION-------------------------------------------#}

           <ul class="navbar-nav mr-auto">

             {% if user.is_authenticated %}

                <li class="nav-item">

                  <a class="nav-link" href="{% url 'app:login' %}">LogIn &nbsp; <i class="fa fa-home" aria-hidden="true"></i> </a>

                </li>


                &nbsp;     &nbsp;     &nbsp;




                <li class="nav-item">

                  <a class="nav-link" href="{% url '#' %}">Sign out &nbsp; <i class="fa fa-sign-out" aria-hidden="true"></i> </a>

                </li>
                 </ul>

            {% else %}

            <li class="nav-item">

              <a class="nav-link" href="{% url 'app:register' %}"> Register </a>

            </li>


            &nbsp;     &nbsp;     &nbsp;


            <li class="nav-item">

              <a class="nav-link" href="{% url 'app:login' %}">Login</a>

            </li>


            {% endif %}

    {#      --------------------------END OF AUTHENTICATION-----------------------------#}

    {#        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">#}
    {#          <ul class="navbar-nav">#}
    {#            <li class="nav-item">#}
    {#              <a class="nav-link " aria-current="page" href="{% url 'app:home' %}">Home</a>#}
    {#            </li>#}
    {#            <li class="nav-item">#}
    {#              <a class="nav-link" href="{% url 'app:libraries' %}">Libraries</a>#}
    {#            </li>#}
    {#            <li class="nav-item">#}
    {#              <a class="nav-link" href="{% url 'app:contacts' %}">Contact us</a>#}
    {#            </li>#}
    {#          </ul>#}
    {#        </div>#}
      </div>
    </nav>
</div>


    <div class="container text-center" >

        <br>
        <br>
        <br>
        <div class="col-5"></div>



            {% block content %}

                <div class="col-4">


                </div>
            {% endblock %}
        <div class="col-3"></div>
    </div>

{#<---main js--->#}
{#<script src="{% static 'js/main' %}"></script>#}

{#<---bootstrap js--->#}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>

</body>
</html>

templates/contacts.html
{% extends 'base.html' %}

{% block content %}

 <section id="contact" class="contact">
      <div class="container" data-aos="fade-up" data-aos-delay="100">

        <div class="row gy-4">
          <div class="col-lg-6">
            <div class="info-item  d-flex flex-column justify-content-center align-items-center">
              <i class="bi bi-map"></i>
              <h3>Our Address</h3>
              <p>A108 Ruku Street, Lavington, Nairobi</p>
            </div>
          </div><!-- End Info Item -->

          <div class="col-lg-3 col-md-6">
            <div class="info-item d-flex flex-column justify-content-center align-items-center">
              <i class="bi bi-envelope"></i>
              <h3>Email Us</h3>
              <p>mika@gmail.com</p>
            </div>
          </div><!-- End Info Item -->

          <div class="col-lg-3 col-md-6">
            <div class="info-item  d-flex flex-column justify-content-center align-items-center">
              <i class="bi bi-telephone"></i>
              <h3>Call Us</h3>
              <p>+254 544 509 315</p>
            </div>
          </div><!-- End Info Item -->
        </div>

        <div class="row gy-4 mt-1">

          <div class="col-lg-6 ">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d31910.49103116015!2d36.734993410839834!3d-1.2872778999999985!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182f1a1ab56e892f%3A0x2089cffb00b87381!2sOsnet%20Gardens%20Resort!5e0!3m2!1sen!2ske!4v1691009375325!5m2!1sen!2ske" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
          </div>
        </div>
      </div>
 </section>
    <!-- End Google Maps --


{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="form-container ">
    <div class="form-group">
        <h1>HELLO :) !!</h1><br>
        <form action="">
            {% csrf_token %}
            {{ form.as_p }}
            <a class="btn btn-success" type="button" href="{% url 'app:libraries' %}">WELCOME</a>
        </form>
    </div>
</div>





{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="form-container ">
    <div class="form-group">
        <h1>HELLO :) !!</h1><br>
        <form action="">
            {% csrf_token %}
            {{ form.as_p }}
            <a class="btn btn-success" type="button" href="{% url 'app:libraries' %}">WELCOME</a>
        </form>
    </div>
</div>





{% endblock %}

templates/libraries.html
{% extends 'base.html' %}

{% block content %}

<div class="container text-centre">
    <div class="table">
        <table>
            <tr>
                <th>Manufacturer</th>
                <th>Model Name</th>
                <th>Model Year</th>
                <th>Engine Capacity</th>
                <th>Price</th>
                <th></th>
            </tr>
            <tr>
                <td>Mercedes</td>
                <td>E350</td>
                <td>2016</td>
                <td>2000CC</td>
                <td>KSH 3,500,000</td>
                <td><a class="btn btn-success" type="button" href="{% url 'app:pay' %}">BUY</a></td>
            </tr>
            <tr>
                <td>Audi</td>
                <td>SQ7</td>
                <td>2019</td>
                <td>3500CC</td>
                <td>KSH 5,000,000</td>
                <td><a class="btn btn-success" type="button" href="{% url 'app:pay' %}">BUY</a></td>
            </tr>
            <tr>
                <td>BMW</td>
                <td>X6</td>
                <td>2022</td>
                <td>3000CC</td>
                <td>KSH 6,000,000</td>
                <td><a class="btn btn-success" type="button" href="{% url 'app:pay' %}">BUY</a></td>
            </tr>
        </table>
    </div>
</div>



{% endblock %}

templates/login.html
{% extends 'base2.html' %}

{% block content %}
<div class="form-container ">
    <div class="form-group">
        <h1>HELLO :) !!</h1><br>
        <form action="">
            {% csrf_token %}
            {{ form.as_p }}
            <a class="btn btn-success" type="button" href="{% url 'app:home' %}">WELCOME</a>
        </form>
    </div>
</div>





{% endblock %}

templates/pay.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">

    <div class="row">


{#              <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">#}
{#                    <strong>{{message}}</strong>#}
{#                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>#}
{#              </div>#}

        <div class="col-md-5">

            <form method="POST" action="{% url 'app:pay'%}">
                {% csrf_token %}

                <label class="form-label mt-5">Phone Number</label>
                <input type="number" name="phone" value="254" class="form-control">

                <label class="form-label mt-5">Amount</label>
                <input type="number" name="amount" class="form-control">

                <input type="submit" name="submit" class="form-control mt-5 btn btn-success" value="pay">
            </form>
        </div>

        <div class="col-md-7">

        </div>

    </div>
</div>



{% endblock %}

templates/register.html
{% extends 'base2.html' %}



{% block content %}

    <div class="container bg-light shadow-md p-5 form-layout">
        <h3> REGISTER</h3>
        <h5>fill the details below to proceed</h5>

        <br>

        <form method="POST" autocomplete="off">
            {% csrf_token %}

            {{ form.as_p }}

            <br>

            <button type="submit" class="btn btn-success btn-block ">REGISTER</button>
        </form>

        <br>
        <div class="text-centre">
            <p> Already have an account?</p> <a href="{% url 'app:login' %}">LogIn</a>
        </div>
    </div>
    <br>





{% endblock %}

templates/token.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

    <div class="row">


              <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                    <strong>{{message}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>

        <div class="col-md-5">

            <form method="POST" action="{% url 'Mpesa:pay'%}">
                {% csrf_token %}

                <label class="form-label mt-5">Phone Number</label>
                <input type="number" name="phone" value="254" class="form-control">

                <label class="form-label mt-5">Amount</label>
                <input type="number" name="amount" class="form-control">

                <input type="submit" name="submit" class="form-control mt-5 btn btn-success" value="pay">
            </form>

        </div>

        <div class="col-md-7">

        </div>

    </div>
</div>




{% endblock %}